import { projectStore } from '../../projectStore';
import { v4 as uuidv4 } from 'uuid';
import { formatToTwoDigits, recreateArrayElement, recreateBranchCircuit, recreateObject } from '../../util';
import { lineConfiguration } from '../../lineStore';
import { pdpConfiguration } from "../../pdpStore";
import { pdpStore } from "../../pdpStore";
import pdpParser from '../../../Excel/pdpParser';
import { pdpBranchCircuitModel } from './pdpBranchCircuitModel';
import { hotPowerBranchCircuitModel } from './hotPowerBranchCircuitModel';

/**
 * creates a new pdp object with default values, all default values should be specified here
 * @returns new pdp with default values
 */
export const pdpModel = {
    create:(index, name) => { 
        const line = projectStore.getState().line;
        const location = name ? name : `PDP${formatToTwoDigits(1+index)}` 
        const pdp = {
          deviceTag:location, 
          amp:"400A", 
          FLA:0,
          line:line, 
          location:location, 
          enclosureSize:"1000x1800x500(WHD)",
          numberOfBusBar:0,
          branchCircuit:pdpModel.initializeBranchCircuits(),
          spare10A:0,
          spare20A:0,
          spare30A:0,
          spare40A:0,
          spare60A:0,
          spare70A:0,
          spare100A:0,
          spare250A:0,
          Opt_SurgeProtectionDevice:false,
          PwrMonitorEnable:false,
          Opt_HotPwrEnable:false,
          hotPowerDrops:[],
          UI:{
            expanded:false,
            icon:"/panel.png",
          },
          data:{
            type:'pdp',
            id:uuidv4(),
          },
          getIndexObject: function(){
            const pdpIndex = this.getIndex();
            return {
              pdpIndex:pdpIndex,
            }
          },
          setValue: function(indexObject, key, value){
            pdpStore.getState().setPdpValue(indexObject, key, value);
          },
          getCB: function(location, cb_dt){
              if(this.location === location){
                const cb = pdpConfiguration.getCB(this.branchCircuit, cb_dt);
                return cb;
              }
              return null;
          },
          getIndex: function(){
            const pdps = pdpStore.getState().pdps;
            return pdps.findIndex(pdp => pdp.data.id === this.data.id)
          },
          getItemById: function(id){
            return pdpConfiguration.getItemById(this, id);
          },
          getNodeData: function(){
            return [
              this.location,
              this.amp,
              this.FLA,
              this.enclosureSize,
            ]
          },
          getStations: function(){
            var stations = []
            Object.keys(this.branchCircuit).forEach(key => {
              stations = lineConfiguration.getStations(this.branchCircuit[key], stations);
            })
            return stations;
          },
          getDevices: function(station){
            var devices = []
            Object.keys(this.branchCircuit).forEach(key => {
              devices = lineConfiguration.getDevices(this.branchCircuit[key], devices, station);
            })
            return devices;
          },
          getCBs:function(location){
            var cbs = []
            if(this.location === location){
              Object.keys(this.branchCircuit).forEach(key => {
                this.branchCircuit[key].forEach(drop => {
                      if(drop.UI.CB_DT){
                          cbs.push(drop.UI.CB_DT);
                      }
                  })
              })
            }
            return cbs;
          },
          setHotPowerBranchCircuit:function(){
            pdpStore.getState().setHotPowerBranchCircuit(this);
          }
        }
    
        return pdp;
    },
    initializeBranchCircuits: () => {
      const branchCircuit = {
        "10A":[],
        "20A":[],
        "30A":[],
        "40A":[],
        "60A":[],
        "70A":[],
        "100A":[],
        "250A":[],
      }

      return branchCircuit;
    },
    /**
     * This function is intended to do the final clean ups and data manipulation and run right before data is send to Model class for IMX generation, 
     * @param {Array} pdps pdp class generated by excel/UI forms
     * @returns finalized pdps objects for model class
     */
    generateData: (pdps) => {
      pdps.forEach(pdp => {
        const numberOfBusBar = pdpParser.getNumberOfBusBar(pdp.enclosureSize);
        pdp.numberOfBusBar = numberOfBusBar;
      });
      return pdps;
    },
    createBranchCircuit: (parent, amperage) => {
      const branchCircuit= {
        PwrDrop_Spare: false,
        DropType: "A-external",
        PwrDrop_DescTxt: "",
        line:parent.line,
        targetLocation: "",
        targetDT: "",
        targetFLA: 0,
        targetFLA_Total: 0,
        targetCableLength:0,
        UI:{
          expanded:false,
          CB_DT:"",
          icon:"/powerdrop.png",
        },
  
        data:{
          type:'cb',
          parent:parent,
          amperage:amperage,
          powertarget:'',
          id:uuidv4(),
        },
        getIndexObject: function(){
          const pdpIndex = this.data.parent.getIndex();
          const branchCircuitIndex = this.getIndex();
          const amperage = this.data.amperage;
          return {
            pdpIndex:pdpIndex,
            branchCircuitIndex:branchCircuitIndex,
            amperage:amperage,
          }
        },
        getIndex: function(){
          return this.data.parent.branchCircuit[amperage].findIndex(drop => drop.data.id === this.data.id)
        },
        setValue: function(indexObject, key, value){
          pdpStore.getState().setBranchCircuitValue(indexObject, key, value, false, false);
        },
        setDataValue: function(key, value){
          const indexObject = this.getIndexObject();
          pdpStore.getState().setBranchCircuitValue(indexObject, key, value, false, true);
        },
        getNodeData: function(){
          return [
            this.data.amperage,
            `${this.TargetDevice_FLA}A`,
            `${this.targetCableLength}m`,
          ]
        },
        getStations: function(){
          return [this.targetLocation,]
        },
        getDevices: function(station){
          if(this.targetLocation  === station){
            return [this.targetDT,]
          }
          return []
        }
      }
  
      return branchCircuit;
    },
    merge: (state, currentState) => { 
      const pdps = state.pdps.map(pdp => {
        var newPdp = recreateObject(pdp, pdpModel.create)

        Object.keys(pdp.branchCircuit).forEach(key => { 
            var array = pdp.branchCircuit[key];
            var branchCircuit = array.map(item => { 
              //const newItem = pdpBranchCircuitModel.create(newPdp, key); 
              const newItem = pdpModel.createBranchCircuit(newPdp, key) 
              Object.assign(newItem, item);
              newItem.data.parent = newPdp;
              return newItem;
            })
            newPdp.branchCircuit[key] = branchCircuit;
        });
        var hotPowerDrops = recreateArrayElement(newPdp, pdp.hotPowerDrops, hotPowerBranchCircuitModel.create)
        newPdp.hotPowerDrops = hotPowerDrops;
        return newPdp;
      })
      state.pdps = pdps;
      Object.assign(currentState, state)
      return currentState
    } 
}
